# config.yml
models:
  - type: main
    engine: ollama
    model: llama3

rails:
  input:
    flows:
      - self check input
      - self check output
  #     - mask sensitive data on input

  # # Output rails are triggered after a bot message has been generated.
  # output:
  #   flows:
  #     - self check facts
  #     - self check hallucination
  #     - activefence moderation
  #     - gotitai rag truthcheck

  # config:
  #   # Configure the types of entities that should be masked on user input.
  #   sensitive_data_detection:
  #     input:
  #       entities:
  #         - PERSON
  #         - EMAIL_ADDRESS
